### ISSUE TITLE
Can't open links

### ISSUE THREAD

**Issue by qrazhan** [imton/MessengerNative#4]
Can't open links in messages.  For example, if someone send you a YouTube link, it should make a nw.Shell.openExternal() call or something.

**Comment by gastonmorixe** [comment]
@qrazhan  yeah, that's because it uses webview right? maybe I should switch to iframe, will it solve this?

**Comment by qrazhan** [comment]
I think so.  I was messing around with the webview APIs today but couldn't really get it to work.

**Comment by gastonmorixe** [comment]
@qrazhan great, if you could give iframe a try would be awesome

```
<iframe nwdisable nwfaketop> (see “Security” for details)
```

https://github.com/nwjs/nw.js/wiki/Security

**Comment by qrazhan** [comment]
yeah i'll take a look into it
