### ISSUE TITLE
WIndows Build, cannot register anyting

### ISSUE THREAD

**Issue by necenzurat** [imton/MessengerNative#5]
did a windows build, cannot click inside of the app
Edit: M$ Win 8.1, 64
The 32 and 64 bit app.

**Comment by jtf323** [comment]
Same issue here, Windows 8.1 x64, 32 and 64 bit version of the app

Edit: Just tried on Windows 7 x64 (The 32 and 64 bit version of the app) with the same result.

**Comment by mashlol** [comment]
The problem here is the line `body{ -webkit-app-region: drag; }`. in the index.

Easiest fix is to add the frame back and remove that line on Windows.

**Comment by necenzurat** [comment]
make a pull request, please :)

**Comment by mashlol** [comment]
@necenzurat I was looking into this yesterday, may or may not have time on the weekend, we shall see..

**Comment by necenzurat** [comment]
you can edit the file live and make a pull request, it's like one minute :)

## 

_Costin Moise_ aka necenzurat

Tel: _+4 0726.459.188_ | Github https://github.com/necenzurat | Linkedin
http://www.linkedin.com/in/necenzurat

**Comment by mashlol** [comment]
> you can edit the file live and make a pull request, it's like one minute :)

Feel free to go ahead and do it then
